### ISSUE TITLE
reconstruction error

### ISSUE THREAD

**Issue by meadow163** [acids-ircam/RAVE#52]
Hi caillonantoine,

Thanks for your brilliant work, your work is amazing.
I just want to try your model using my data, but I think I got some wrong result. My training now is on the first stage(just VAE part) and my epoch is 1220, so my global step is 1220 * 32(batch), the curve is like this:

![image](https://user-images.githubusercontent.com/30004294/165291249-fcbe2752-45ec-49d4-9eff-faa96da4366f.png)

My config is as follow:

```yaml
DATA_SIZE : 16
CAPACITY : 64
LATENT_SIZE : 128
RATIOS : [4, 4, 4, 2]
BIAS : True
NO_LATENCY : False

MIN_KL : 1e-1
MAX_KL : 1e-1
CROPPED_LATENT_SIZE : 0
FEATURE_MATCH : True

LOUD_STRIDE : 1

USE_NOISE : True
NOISE_RATIOS : [4, 4, 4]
NOISE_BANDS : 5

D_CAPACITY : 16
D_MULTIPLIER : 4
D_N_LAYERS : 4

WARMUP : 1000000
MODE : "hinge"


SR : 22050
N_SIGNAL : 655360
MAX_STEPS : 3000000

BATCH : 32
NAME : 'rave'
```

my original wav is:
![image](https://user-images.githubusercontent.com/30004294/165292358-54f3936e-87fd-484c-b961-f4d34e53dc33.png)

and my reconstruction wav is:
![image](https://user-images.githubusercontent.com/30004294/165292425-77fd31c0-258b-45fb-9913-1d32c9ccb9e4.png)

Is that normal? I think may be some issues with my training.

can you give me some suggestions about this issue, please?

Thanks in advance!

Best,
